x-common-variables: &common-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}
  JWT_ALGORITHM: ${JWT_ALGORITHM}
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}

x-common-backend: &common-backend
  build:
    context: ../../backend
    dockerfile: Dockerfile
  networks:
    - app-network
  depends_on:
    postgres:
      condition: service_healthy

x-common-frontend: &common-frontend
  build:
    context: ../../frontend
    dockerfile: Dockerfile
  networks:
    - app-network
  depends_on:
    - backend

services:
  postgres:
    image: postgres:15
    environment:
      <<: *common-variables
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    <<: *common-backend
    environment:
      <<: *common-variables
      DATABASE_URL: ${DATABASE_URL}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}

  frontend:
    <<: *common-frontend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
