services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dellabeneta/sistema-cadastro-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dellabeneta/sistema-cadastro-frontend:latest
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
