services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-dev
      POSTGRES_PASSWORD: user-pass
      POSTGRES_DB: user-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    volumes:
      - ./backend:/app:cached
      - ./backend/tests:/app/tests:cached
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      ENVIRONMENT: development
      DEBUG: 1
      DATABASE_URL: postgresql://user-dev:user-pass@postgres:5432/user-db
      JWT_SECRET_KEY: user-devscret-this
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
