services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sistema_cadastro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: 
      context: ../../backend
      dockerfile: Dockerfile
    volumes:
      - ../../backend:/app:cached
      - ../../backend/tests:/app/tests:cached
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
      - DEBUG=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ../../frontend:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

volumes:
  postgres_data_dev:
