name: CI/CD Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Droplet
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar chave SSH para conexão
      - name: Configure SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAVE_SSH }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # 3. Conectar via SSH e executar comandos remotos
      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }} << 'EOF'
            mkdir -p /data/app
            cd /data/app
            if [ -d ".git" ]; then
              echo "Directory exists. Pulling latest changes..."
              git reset --hard
              git clean -fd
              git pull origin main
            else
              echo "Directory does not exist. Cloning repository..."
              git clone git@github.com:dellabeneta/python-peoples-crud.git .
            fi
          EOF