name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_SSH_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          # Usar caminho absoluto
          cd /home/${{ secrets.DO_SSH_USER }}/python-peoples-crud
          
          # Garantir que o repositório está atualizado
          git fetch --all
          git reset --hard origin/main
          
          # Usar docker-compose com hífen
          docker-compose -f config/docker-compose.yml down
          docker-compose -f config/docker-compose.yml up -d --build